stages:
- build
- test
- deploy

build_maven:
  stage: build
  script:
   - echo "build unittest....."
   - echo "done"
  only:
   - master
  tags:
   - gitlab-runner_unittest 


deploy_springboot:
  stage: deploy
  script:
   - echo "deploy unittest...."
   - /home/deploy_project/gitlab_deploy/deploy_unittest.sh
   - echo "done"
  only:
   - master
  tags:
   - gitlab-runner_unittest  
