stages:
- build
- test
- deploy

build_maven:
  stage: build
  script:
   - echo "build unittest....."
   - echo "done"
  only:
   - master
  tags:
   - slave-centos7-runner


deploy_springboot:
  stage: deploy
  script:
   - echo "deploy unittest...."
   - echo "done"
  only:
   - master
  tags:
   - slave-centos7-runner 
